ThoughtShare/config/routes.rb
ThoughtShare::Application.routes.draw do
  
  post "thoughts/activate_thinker"
  post "thoughts/thumbup"
  
  resources :thoughts, :thinkers
  
  match ':controller/:action/:id', :controller => :thoughts, :action => :thumbers
  
  root :to => 'thoughts#index'
  

end

ThoughtShare/app/models/follow.rb
class Follow < ActiveRecord::Base
  belongs_to :follower, :foreign_key => "follower_id", :class_name => "Thinker"
  belongs_to :followee, :foreign_key => "followee_id", :class_name => "Thinker"
end

ThoughtShare/app/models/thinker.rb
class Thinker < ActiveRecord::Base
  has_many :follows, :foreign_key => "follower_id", :class_name => "Follow"
  has_many :followed, :foreign_key => "followee_id", :class_name => "Follow"
  has_many :thoughts
  has_many :thumbs

  validates :name, :length => { :minimum => 1, :maximum => 35 }, :uniqueness => true
  validates_format_of :name, :with => /\A[A-Z||a-z][-A-Za-z0-9 ']*\Z/

  validates :url, :length => { :maximum => 120 }, :uniqueness => true
  validates_format_of :url, :with => URI::regexp(%w(http https))
  
  validates_format_of :email, :with => /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/
end

ThoughtShare/app/models/thought.rb
class Thought < ActiveRecord::Base
  belongs_to :thinker
  has_many :thumbs
  validates :thought, :length => { :minimum => 5, :maximum => 154 }, :uniqueness => true
end

ThoughtShare/app/models/thumb.rb
class Thumb < ActiveRecord::Base
	belongs_to :thinker
	belongs_to :thought	
end

ThoughtShare/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

ThoughtShare/app/controllers/thinkers_controller.rb
class ThinkersController < ApplicationController
  # GET /thinkers
  # GET /thinkers.json
  def index
    @thinkers = Thinker.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @thinkers }
    end
  end

  # GET /thinkers/1
  # GET /thinkers/1.json
  def show
    @thinker = Thinker.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @thinker }
    end
  end

  # GET /thinkers/new
  # GET /thinkers/new.json
  def new
    @thinker = Thinker.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @thinker }
    end
  end

  # GET /thinkers/1/edit
  def edit
    @thinker = Thinker.find(params[:id])
  end

  # POST /thinkers
  # POST /thinkers.json
  def create
    @thinker = Thinker.new(params[:thinker])

    respond_to do |format|
      if @thinker.save
        format.html { redirect_to @thinker, notice: 'Thinker was successfully created.' }
        format.json { render json: @thinker, status: :created, location: @thinker }
      else
        format.html { render action: "new" }
        format.json { render json: @thinker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /thinkers/1
  # PUT /thinkers/1.json
  def update
    @thinker = Thinker.find(params[:id])

    respond_to do |format|
      if @thinker.update_attributes(params[:thinker])
        format.html { redirect_to @thinker, notice: 'Thinker was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @thinker.errors, status: :unprocessable_entity }
      end
    end
  end

end

ThoughtShare/app/controllers/thoughts_controller.rb
class ThoughtsController < ApplicationController
  # GET /thoughts
  # GET /thoughts.json
  def index
	@thinkers = Thinker.all
	load_active_thinker
	
	#Depending on our filter, show different thoughts
	params[:show] && session[:show] = params[:show] #if params[:show] is nil, don't assign
	if session[:show] == 'following'
	then
		@thoughts = Thought.joins(:thinker => :followed).where(:follows => {:follower_id => @active_thinker.id})
     
     elsif session[:show] == 'mine'
          #Show only thoughts for the active user
          @thoughts = Thought.where(:thinker_id => @active_thinker.id)

	elsif session[:show] == 'popular'
	     #Show all thoughts with at least one thumb, sorted by number of thumbs descendingly
          @thoughts = Thought.joins(:thumbs).group(:thought).order("count(*) DESC")

     else
		@thoughts = Thought.all
     end
	
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @thoughts }
    end
  end

  # GET /thoughts/1
  # GET /thoughts/1.json
  def show
    @thought = Thought.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @thought }
    end
  end

  # GET /thoughts/new
  # GET /thoughts/new.json
  def new
    @thought = Thought.new
    
    load_active_thinker

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @thought }
    end
  end

  # GET /thoughts/1/edit
  def edit
    @thought = Thought.find(params[:id])
  end

  # POST /thoughts
  # POST /thoughts.json
  def create
    load_active_thinker
    @thought = Thought.new(params[:thought])
	@thought.thinker = @active_thinker
	
    respond_to do |format|
      if @thought.save
        format.html { redirect_to @thought, notice: 'Thought was successfully created.' }
        format.json { render json: @thought, status: :created, location: @thought }
      else
        format.html { render action: "new" }
        format.json { render json: @thought.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /thoughts/1
  # PUT /thoughts/1.json
  def update
    @thought = Thought.find(params[:id])

    respond_to do |format|
      if @thought.update_attributes(params[:thought])
        format.html { redirect_to @thought, notice: 'Thought was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @thought.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /thoughts/1
  # DELETE /thoughts/1.json
  def destroy
    @thought = Thought.find(params[:id])
    @thought.destroy

    respond_to do |format|
      format.html { redirect_to thoughts_url }
      format.json { head :ok }
    end
  end
  
  # Change the active user
  # POST /thoughts/activate_thinker/1
  def activate_thinker
  	session[:active_thinker] = params[:active_thinker][:id]
    @active_thinker = Thinker.find(params[:active_thinker][:id])
    
    respond_to do |format|
      format.html { redirect_to :action => 'index' }
      format.json { render json: @thoughts }
    end
  end
  
  def load_active_thinker
  	begin
  		@active_thinker ||= Thinker.find(session[:active_thinker])
  	rescue 
  		@active_thinker = nil
  	end
  	@active_thinker ||= Thinker.last
  end

  def thumbup
  	load_active_thinker

	if !Thumb.exists?(["thinker_id = #{@active_thinker.id} AND thought_id = #{params[:thought][:id]}"])
	  Thumb.create({thought_id: params[:thought][:id], thinker: @active_thinker})
	end

  	respond_to do |format|
      format.html { redirect_to :action => 'index' }
      format.json { render json: @thoughts }
    end
  end
  
  def thumbers
	@thumbers = Thumb.where(:thought_id => params[:id]).group(:thinker_id)
	
	respond_to do |format|
      format.html # redirect_to :action => 'thumbers' 
      format.json { render json: @thumbers }
    end
  end

end

ThoughtShare/app/helpers/home_helper.rb
module HomeHelper
end

ThoughtShare/app/helpers/shares_helper.rb
module SharesHelper
end

ThoughtShare/app/helpers/thinkers_helper.rb
module ThinkersHelper
end

ThoughtShare/app/helpers/thoughts_helper.rb
module ThoughtsHelper
end

ThoughtShare/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ThoughtShare!!</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
</head>
<body>
<div id=container>

	<div id=thinkerbar> 
		<%= form_tag("/thoughts/activate_thinker", :method => "post", :id => "activethinkerform" ) do %>
		Logged in as: 
		  <%= select("active_thinker", "id", 
		  			 Thinker.all.collect{ |t| [t.name, t.id] },
		  			 { :selected => session[:active_thinker] }, 
		  			 { :onchange => "submit()" }
		  			 ) %>
		<% end %>
	</div>
	
	
	<%= link_to "Share a Thought", new_thought_path, {:id => "thinklink"} %>
	
	<%= link_to "Thinkers", thinkers_path(@index), {:id => "thinklink"} %>
	
	<%= link_to "Home", thoughts_path(@index), {:id => "thinklink"} %>

	<div class=clear></div>

	<%= yield %>

</div>
</body>
</html>

ThoughtShare/app/views/thinkers/_form.html.erb
<%= form_for(@thinker) do |f| %>
  <% if @thinker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@thinker.errors.count, "error") %> prohibited this thinker from being saved:</h2>

      <ul>
      <% @thinker.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  
  <div class="field">
	<%= f.label :email %><br />
	<%= f.text_field :email %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ThoughtShare/app/views/thinkers/edit.html.erb
<h1>Editing thinker</h1>

<%= render 'form' %>

<%= link_to 'Show', @thinker %> |
<%= link_to 'Back', thinkers_path %>

ThoughtShare/app/views/thinkers/index.html.erb
<h1>Listing thinkers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>URL</th>
	<th>Email</th>
    <th></th>
  </tr>

<% @thinkers.each do |thinker| %>
  <tr>
  	<td><%= link_to thinker.name, thinker %></td>
  	<td><%= link_to thinker.url, thinker.url%></td>
	<td><%= mail_to thinker.email, thinker.email%></td>
    <td><%= link_to 'Edit', edit_thinker_path(thinker) %></td>
    <td></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Thinker', new_thinker_path %>

ThoughtShare/app/views/thinkers/new.html.erb
<h1>New thinker</h1>

<%= render 'form' %>

<%= link_to 'Back', thinkers_path %>

ThoughtShare/app/views/thinkers/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%=@thinker.name%></h1>
<h2><%=@thinker.url%></h2>

<div class=email>
<h3>Email</h3>
<% if @thinker.email != nil %>
	<%=@thinker.email%>
<% else %>
	<%= @thinker.name + "has no email." %>
<% end %>
</div>

<div class=following>
<h3>Following</h3>

<% 
following = Thinker.joins(:followed).where(:follows => {:follower_id => @thinker.id})
if following.empty? then %>
		<div><%=@thinker.name%> is not following anybody.</div>
<% else %> 
	<% following.each do |thinker| %>
		<% if thinker %>
			<div><%= link_to thinker.name,thinker %></div>
		<% end %>
	<% end %>
<% end %>
</div>

<div class=followed>
<h3>Followed By</h3>
<% followed = Thinker.joins(:follows).where(:follows => {:followee_id => @thinker.id})
if followed.empty? %>
	<div><%=@thinker.name%> is not followed by anybody.</div>
<% else %>
	<% followed.each do |thinker| %>
		<% if thinker %>
			<div><%= link_to thinker.name,thinker %></div>
		<% end %>
	<% end %>
<% end %>
</div>
	
<div class=clear></div>
	
<div>
<%= link_to "Edit", edit_thinker_path(@thinker) %> |
<%= link_to "Home", thoughts_path %>
</div>

ThoughtShare/app/views/thoughts/_form.html.erb
<%= form_for(@thought) do |f| %>

  <% if @thought.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@thought.errors.count, "error") %> prohibited this thought from being saved:</h2>

      <ul>
      <% @thought.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :thought %><br />
    <%= f.text_area :thought %>
  </div>
  
  <div class=thought-name>
  	<%= @active_thinker.name %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ThoughtShare/app/views/thoughts/edit.html.erb
<h1>Editing thought</h1>

<%= render 'form' %>

<%= link_to 'Show', @thought %> |
<%= link_to 'Back', thoughts_path %>

ThoughtShare/app/views/thoughts/index.html.erb
<h1>Thoughts</h1>

<div id=thoughttab>
<ul>
	<li><a id=active_a_<%=session[:show]%> href="?show=all">All</a></li>
	<li><a id=active_p_<%=session[:show]%> href="?show=popular">Popular</a></li> 
     <li><a id=active_f_<%=session[:show]%> href="?show=following">Following</a></li>
     <li><a id=active_m_<%=session[:show]%> href="?show=mine">Mine</a></li>
</ul>
</div>


<div id=thoughts>

<%=@thoughts.empty? ? "No thoughts here." : ""%>
<% @thoughts.each do |thought| %>
<div class=thought> 
	<div class=thoughtquote> <%= thought.thought %> </div>

	<div class=thumbs> 
		<%= form_tag("thoughts/thumbup") do %>
			<%= hidden_field(:thought, :id, :value=>thought.id) %>
			<div class=thumbups>
				<%= submit_tag("Thumb!", {:type => :image, :src => "/images/thumbup.png", :width => 15}) %> 
				<a href="/thoughts/thumbers/<%=thought.id%>"><%=thought.thumbs.size %></a>
			</div>
		<% end %>
	</div>
	
	<div class=thinker-name> <%= link_to thought.thinker.name, thought.thinker %> </div>
	<div class=thinker-url> <%= link_to thought.thinker.url, thought.thinker.url %> </div>
</div>
<% end %>

</div>

<br />


ThoughtShare/app/views/thoughts/new.html.erb
<h1>New thought</h1>

<%= render 'form' %>

<%= link_to 'Back', thoughts_path %>

ThoughtShare/app/views/thoughts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Thinker:</b>
  <%= @thought.thinker %>
</p>

<p>
  <b>Thought:</b>
  <%= @thought.thought %>
</p>


<%= link_to 'Edit', edit_thought_path(@thought) %> |
<%= link_to 'Back', thoughts_path %>

ThoughtShare/app/views/thoughts/thumbers.html.erb
<div id=thought>
	<% thought = Thought.find(params[:id]) %>
	
	<div class=thoughtquote>
		<h1>
			<%= thought.thought %>
		</h1>
	</div>
	
	<div class=thinker>
		<h3>
			A thought by  <%= link_to thought.thinker.name, thought.thinker %>
		</h3>
	</div>
	
	<br />
	<div class=thumbers>
		<h2>
			Thumbers of this thought:
		</h2>
			<div class=thumbername>
				<% if @thumbers.length == 0 %>
					<%= "There are no thumbers for this thought." %>
				<% else %>
					<% @thumbers.each do |thumber| %>
						<% if thumber.thinker %>
							<%= link_to thumber.thinker.name, thumber.thinker %><br />
						<% end %>
					<% end %>
				<% end %>
			</div>
	</div>
	
</div>

<p>
<br />
<%= link_to "Back", thoughts_path %> | 
<%= link_to "Home", thoughts_path %>
</p>